// export const [data, setData] = [
//   {
//     ticketRefNum: "tck0001",
//     title: "routing problem",
//     status: "completed",
//     createdBy: "abi",
//     assignedTo: "ram",
//     difficultyLevel: "high",
//     startDate: "07/12/2023",
//     due: 3,
//   },
//   {
//     ticketRefNum: "tck0001",
//     title: "routing problem",
//     status: "pending",
//     createdBy: "abi",
//     assignedTo: "ram",
//     difficultyLevel: "medium",
//     startDate: "07/12/2023",
//     due: 3,
//   },
//   {
//     ticketRefNum: "tck0001",
//     title: "routing problem",
//     status: "hold",
//     createdBy: "abi",
//     assignedTo: "ram",
//     difficultyLevel: "medium",
//     startDate: "07/12/2023",
//     due: 3,
//   },
//   {
//     ticketRefNum: "tck0001",
//     title: "routing problem",
//     status: "completed",
//     createdBy: "abi",
//     assignedTo: "ram",
//     difficultyLevel: "low",
//     startDate: "07/12/2023",
//     due: 3,
//   },
// ];
